---
title: "ProyectoEstadistica1"
output: html_document
date: '2023-08-26'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r warning=FALSE, message=FALSE}
library(readr)

datosOriginales <- read_csv("proyesta.csv")
datos <- datosOriginales %>%
  rename(
    EnfermedadCardiaca = HeartDisease,
    BMI = BMI,
    Fumador = Smoking,
    ConsumoAlcohol = AlcoholDrinking,
    AccidenteCerebrovascular = Stroke,
    SaludFisica = PhysicalHealth,
    SaludMental = MentalHealth,
    DificultadCaminar = DiffWalking,
    Sexo = Sex,
    CategoriaEdad = AgeCategory,
    SaludGeneral = GenHealth,
    TiempoSueno = SleepTime,
    Asma = Asthma,
    EnfermedadRenal = KidneyDisease,
    CancerPiel = SkinCancer,
    Raza = Race,
    Diabetes = Diabetic,
    ActividadFisica = PhysicalActivity
  )

traduccion_saludGeneral <- c(
  "Excelente",
  "Regular",
  "Bueno",
  "Malo",
  "Muy bueno"
)
datos <- datos %>%
  mutate(SaludGeneral = factor(SaludGeneral, levels = c("Excellent", "Fair", "Good", "Poor", "Very good"), labels = traduccion_saludGeneral))

```
Gr치ficos.

1. Gr치fico BMI y Enfermedad Cardiaca

```{r}
datos_filtrados <- datos[datos$BMI < 50, ]

BMICardiaca <- ggplot(datos_filtrados, aes(x = EnfermedadCardiaca, y = BMI, fill = EnfermedadCardiaca)) +
  geom_boxplot() +
  labs(x = "Enfermedad Cardiaca", y = "BMI") +
  scale_fill_manual(values = c("lightblue", "lightgreen")) 

print(BMICardiaca)
```

2. Gr치fico BMI y derrame Cerebral

```{r}
BMICerebral <- ggplot(datos_filtrados, aes(x = AccidenteCerebrovascular, y = BMI, fill = AccidenteCerebrovascular)) +
  geom_boxplot() +
  labs(x = "Derrame Cerebral", y = "BMI",fill = "Derrame Cerebral") +
  scale_fill_manual(values = c("lightblue", "lightgreen")) 

print(BMICerebral)
```
3. Distribuci칩n de imc

```{r}
bmicat <- datos$BMI %>% cut(datos$BMI, 
                       breaks = c(0, 18.5, 24.9, 29.9, Inf), 
                       labels = c("<18.5", "18.5 - 24.9", "25.0 - 29.9", "30.0<"),
                       right = FALSE)

distimc <- ggplot(datos, aes(x = bmicat, fill = bmicat)) +
  geom_bar() +
  labs(x = "Nivel de IMC", y = "Frecuencia",fill = "Nivel IMC") +
  scale_fill_manual(values = c("lightblue", "lightgreen", "lightpink", "lightgray")) +
  theme_minimal()
print(distimc)
```


